#49 ServiceTypes - обновлено Добавлено: open_and_load_zip_backup() и выгрузка всех файлов в архиве (main.py строка 469)
Прблема: архив не высылается, ошибка в логах:

requests.exceptions.SSLError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1855638451:AAE7In1lFi4lh6HAZiJnhlRBoZlbZnni5PQ/sendDocument?chat_id=1342906930 (Caused by SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2423)')))